// Code generated by gencol. DO NOT EDIT.
package meta

var Address = struct {
	Id string
	Address string
	IsActive string
	CreatedAt string
	UpdatedAt string
}{
	Id: "id",
	Address: "address",
	IsActive: "is_active",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}