// Code generated by gencol. DO NOT EDIT.
package meta

var User = struct {
	Id string
	Username string
	Password string
	Phone string
	Email string
	IsActive string
	CreatedAt string
	UpdatedAt string
}{
	Id: "id",
	Username: "username",
	Password: "password",
	Phone: "phone",
	Email: "email",
	IsActive: "is_active",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}