package main

import (
	"bufio"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"unicode"
)

const version = "v1.0.3"

var colReg = regexp.MustCompile(`column:\s*([^;"]+)`)

type fieldMeta struct {
	FieldName string
	ColName   string
}

type structMeta struct {
	StructName string
	PkgName    string
	Fields     []fieldMeta
}

// 本地安装: go install .
// 获取 tag: git tag
// 加 tag: git tag v1.0.0
// 推送 tag: git push --tags
func main() {
	verFlag := flag.Bool("v", false, "show version")
	flag.Parse()
	if *verFlag {
		fmt.Printf("gencol version %s\n", version)
		return
	}

	args := flag.Args()
	var srcDir, outDir string

	// 不带参数：交互式问答模式
	if len(args) == 0 {
		srcDir = readPrompt("Enter model source directory", "./internal/models")
		outDir = readPrompt("Enter output directory for generated files", "./internal/meta")
		fmt.Printf("\nSource dir: %s\nOutput dir: %s\nStart generating...\n\n", srcDir, outDir)
	} else if len(args) == 2 {
		// 两个参数，直接执行（go generate用）
		srcDir = args[0]
		outDir = args[1]
	} else {
		fmt.Println("Usage:")
		fmt.Println("  gencol                     # Interactive prompt mode")
		fmt.Println("  gencol <modelDir> <outDir> # Silent mode with directories")
		fmt.Println("  gencol -v                  # Show version")
		fmt.Println("Example: gencol ./internal/models ./internal/meta")
		os.Exit(1)
	}

	files, err := scanDir(srcDir)
	if err != nil {
		fmt.Printf("scan dir error: %v\n", err)
		os.Exit(1)
	}

	for _, file := range files {
		structList, err := parseFile(file)
		if err != nil {
			fmt.Printf("⚠️ parse %s failed: %v\n", file, err)
			continue
		}
		if len(structList) == 0 {
			continue
		}
		base := filepath.Base(file)
		modelName := strings.TrimSuffix(base, filepath.Ext(base))
		err = genFile(modelName, outDir, structList)
		if err != nil {
			fmt.Printf("generate %s error: %v\n", modelName, err)
			os.Exit(1)
		}
	}
	fmt.Println("\n🎉 all generate done")
}

// parseFile 解析单个go文件，提取里面所有struct
func parseFile(path string) ([]structMeta, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, path, nil, parser.AllErrors)
	if err != nil {
		return nil, err
	}
	pkg := node.Name.Name
	var structs []structMeta
	ast.Inspect(node, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok {
			return true
		}
		st, ok := ts.Type.(*ast.StructType)
		if !ok {
			return true
		}
		structName := ts.Name.Name
		var fields []fieldMeta
		for _, f := range st.Fields.List {
			if len(f.Names) == 0 {
				continue
			}
			goField := f.Names[0].Name
			if f.Tag == nil {
				continue
			}
			tag := strings.Trim(f.Tag.Value, "`")
			match := colReg.FindStringSubmatch(tag)
			if len(match) < 2 {
				continue
			}
			dbCol := strings.TrimSpace(match[1])
			dbCol = strings.Trim(dbCol, `"`) // 去除捕获到的首尾双引号
			fields = append(fields, fieldMeta{
				FieldName: goField,
				ColName:   dbCol,
			})
		}
		if len(fields) > 0 {
			structs = append(structs, structMeta{
				StructName: structName,
				PkgName:    pkg,
				Fields:     fields,
			})
		}
		return false
	})
	return structs, nil
}

// genFile 单个模型文件生成meta下独立文件
// srcBaseName: user.go -> user
// outDir: ./internal/meta
func genFile(srcBaseName string, outDir string, structs []structMeta) error {
	if len(structs) == 0 {
		return nil
	}
	err := os.MkdirAll(outDir, 0755)
	if err != nil {
		return err
	}
	outName := srcBaseName + ".go"
	outPath := filepath.Join(outDir, outName)

	f, err := os.Create(outPath)
	if err != nil {
		return err
	}
	defer f.Close()
	w := bufio.NewWriter(f)
	defer w.Flush()

	fmt.Fprintf(w, "// Code generated by gencol. DO NOT EDIT.\n")
	fmt.Fprintf(w, "package meta\n\n")

	for _, st := range structs {
		fmt.Fprintf(w, "var %s = struct {\n", st.StructName)
		for _, fd := range st.Fields {
			fmt.Fprintf(w, "\t%s string\n", fd.FieldName)
		}
		fmt.Fprintf(w, "}{\n")
		for _, fd := range st.Fields {
			fmt.Fprintf(w, "\t%s: %q,\n", fd.FieldName, fd.ColName) // ✅ 去掉外层引号
		}
		fmt.Fprintf(w, "}")
	}

	fmt.Printf("✅ generated: %s\n", outPath)
	return nil
}

// scanDir 遍历目录，收集所有go文件，跳过test文件
func scanDir(root string) ([]string, error) {
	var files []string
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		if filepath.Ext(path) != ".go" {
			return nil
		}
		if strings.HasSuffix(path, "_test.go") {
			return nil
		}
		files = append(files, path)
		return nil
	})
	return files, err
}

// readPrompt 读取控制台输入，支持默认值，默认值灰色ANSI
func readPrompt(prompt string, def string) string {
	scanner := bufio.NewScanner(os.Stdin)
	// 90 = light gray; 0 reset color
	// \033[90m  → 开启浅灰色
	// %s        → 要显示的文本（./internal/models）
	// \033[0m   → 关闭颜色，恢复正常
	fmt.Printf("%s \033[90m%s\033[0m: ", prompt, def)
	scanner.Scan()
	input := strings.TrimSpace(scanner.Text())
	if input == "" {
		return def
	}
	return input
}

// lowerFirst 首字母小写，其余字符保持不变 RoleModel → roleModel
func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}

// camelToSnake 大驼峰转下划线小写 RoleModel → role_model
func camelToSnake(s string) string {
	var buf strings.Builder
	for i, r := range s {
		if unicode.IsUpper(r) {
			if i > 0 {
				buf.WriteRune('_')
			}
			buf.WriteRune(unicode.ToLower(r))
		} else {
			buf.WriteRune(r)
		}
	}
	return buf.String()
}

func gencol_test() {
	main()
}
